name: eloudcry
description: A project aimed at stifling rape/accidental cases in Nigeria

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^8.1.2
  geolocation: ^1.1.2
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_audio_recorder: ^0.5.5
  flutter_secure_storage: ^3.3.1+1
  flutter_sms: ^2.0.1+2
  riverpod: ^0.13.1
  hooks_riverpod: ^0.13.1
  firebase_auth: ^2.0.0
  firebase_storage: ^9.0.0
  image_picker: ^0.8.1+3
  cupertino_icons: ^0.1.2
  device_info: ^0.4.2+4
  get_it: ^4.0.2
  avatar_glow: ^1.2.0
  otp_text_field: ^1.1.1
  cloud_firestore: ^2.3.0
  package_info: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

