name: eloudcry
description: A project aimed at stifling rape/accidental cases in Nigeria

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^8.1.2
  geolocation: ^1.1.2
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_secure_storage: ^4.2.0
  flutter_sms: ^2.0.1+2
  riverpod: ^0.13.1
  hooks_riverpod: ^0.13.1
  firebase_auth: ^2.0.0
  firebase_storage: ^9.0.0
  path_provider: ^2.0.1
  flutter_sound: 8.1.9
  image_picker: ^0.8.1+3
  cupertino_icons: ^0.1.2
  json_annotation: ^4.0.0
  device_info: ^0.4.2+4
  get_it: ^4.0.2
  avatar_glow: ^1.2.0
  otp_text_field: ^1.1.1
  cloud_firestore: ^2.3.0
  package_info: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.2
  json_serializable: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/comfortaa_regular.ttf
        - asset: assets/fonts/comfortaa_medium.ttf
          weight: 400
        - asset: assets/fonts/comfortaa_bold.ttf
          weight: 700
        - asset: assets/fonts/comfortaa_light.ttf
          weight: 300
        - asset: assets/fonts/comfortaa_semibold.ttf
          weight: 500

